/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsList: typeof import('./components/ActionsList.vue')['default']
    ConditionsList: typeof import('./components/ConditionsList.vue')['default']
    EditableField: typeof import('./components/EditableField.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./components/Rule.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Test: typeof import('./pages/Test.vue')['default']
  }
}
