/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    JsonPreview: typeof import('./components/JsonPreview.vue')['default']
    List: typeof import('./components/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./components/Rule.vue')['default']
    RulePreview: typeof import('./components/RulePreview.vue')['default']
  }
}
